apiVersion: v1
kind: Service
metadata:
  name: devops-task
  namespace: devops-task
  labels:
    app: devops-task
spec:
  type: LoadBalancer
  selector:
    app: devops-task
  ports:
    - name: http
      port: 80          # external port
      targetPort: 3000  # containerPort from your Deployment
      protocol: TCP

